// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Ft2OhYFRxPrbW7MfBVOjsuFKrgt4oj4',
    appId: '1:538194311122:web:44888d18efc3a8328cfa0b',
    messagingSenderId: '538194311122',
    projectId: 'murad-agency',
    authDomain: 'murad-agency.firebaseapp.com',
    storageBucket: 'murad-agency.appspot.com',
    measurementId: 'G-HYT3K94114',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX5HOXa8lDyWuy4p76WENNIfd6_gfcMb0',
    appId: '1:538194311122:android:276a651e703c89df8cfa0b',
    messagingSenderId: '538194311122',
    projectId: 'murad-agency',
    storageBucket: 'murad-agency.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtXiRRprPoKI0Wtk8k1Hz2gMlXTMTvrds',
    appId: '1:538194311122:ios:ce9f644b7f81cb8a8cfa0b',
    messagingSenderId: '538194311122',
    projectId: 'murad-agency',
    storageBucket: 'murad-agency.appspot.com',
    androidClientId: '538194311122-rnfaucld4e2in6p54ocun8spr4qu0qsr.apps.googleusercontent.com',
    iosClientId: '538194311122-cj2kf532gl18aherp02c3ptvvc5voq51.apps.googleusercontent.com',
    iosBundleId: 'com.example.outdorCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtXiRRprPoKI0Wtk8k1Hz2gMlXTMTvrds',
    appId: '1:538194311122:ios:ce9f644b7f81cb8a8cfa0b',
    messagingSenderId: '538194311122',
    projectId: 'murad-agency',
    storageBucket: 'murad-agency.appspot.com',
    androidClientId: '538194311122-rnfaucld4e2in6p54ocun8spr4qu0qsr.apps.googleusercontent.com',
    iosClientId: '538194311122-cj2kf532gl18aherp02c3ptvvc5voq51.apps.googleusercontent.com',
    iosBundleId: 'com.example.outdorCalculator',
  );
}
